### ISSUE TITLE
L5-Start already has code for lesson 5

### ISSUE THREAD

**Issue by mullaney** [Code-Pop/Vue-3-Forms#5]
Just a note that I think the l5-start branch has the code for that lesson already added.

(great course, btw, thanks!)

**Comment by marina-mosti** [comment]
Hello @mullaney thank you for bringing this to my attention. Looks like I failed at branch juggling 😂

> (great course, btw, thanks!)

Happy to hear you're enjoying it! Stay tuned for more :D
